name: etf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1o
  - pip
  - python=3.7.13
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - adal==1.2.7
      - applicationinsights==0.11.10
      - argcomplete==2.0.0
      - asn1crypto==1.5.1
      - azure-common==1.1.28
      - azure-core==1.22.1
      - azure-graphrbac==0.61.1
      - azure-identity==1.7.0
      - azure-keyvault-secrets==4.2.0
      - azure-mgmt-authorization==2.0.0
      - azure-mgmt-containerregistry==9.1.0
      - azure-mgmt-core==1.3.0
      - azure-mgmt-keyvault==9.3.0
      - azure-mgmt-resource==20.1.0
      - azure-mgmt-storage==19.1.0
      - azure-storage-blob==12.11.0
      - azureml-automl-core==1.41.1.post1
      - azureml-core==1.41.0.post3
      - azureml-dataprep==3.1.3
      - azureml-dataprep-native==38.0.0
      - azureml-dataprep-rslex==2.5.4
      - azureml-dataset-runtime==1.41.0
      - azureml-pipeline==1.41.0
      - azureml-pipeline-core==1.41.0
      - azureml-pipeline-steps==1.41.0
      - azureml-sdk==1.41.0
      - azureml-telemetry==1.41.0
      - azureml-train-automl-client==1.41.0
      - azureml-train-core==1.41.0
      - azureml-train-restclients-hyperdrive==1.41.0
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==3.2.2
      - boto3==1.23.2
      - botocore==1.26.2
      - cffi==1.15.0
      - chardet==4.0.0
      - charset-normalizer==2.0.12
      - cloudpickle==2.0.0
      - contextlib2==21.6.0
      - cryptography==3.4.8
      - distro==1.7.0
      - docker==5.0.3
      - dotnetcore2==2.1.23
      - fusepy==3.0.1
      - greenlet==1.1.2
      - humanfriendly==10.0
      - idna==3.3
      - importlib-metadata==4.11.3
      - isodate==0.6.1
      - jeepney==0.8.0
      - jmespath==0.10.0
      - joblib==1.1.0
      - jsonpickle==2.2.0
      - knack==0.9.0
      - msal==1.17.0
      - msal-extensions==0.3.1
      - msrest==0.6.21
      - msrestazure==0.6.4
      - ndg-httpsclient==0.5.1
      - numpy==1.21.6
      - oauthlib==3.2.0
      - oscrypto==1.3.0
      - packaging==21.3
      - pandas==1.2.5
      - paramiko==2.11.0
      - pathspec==0.9.0
      - pip==22.1
      - pkginfo==1.8.2
      - portalocker==2.4.0
      - pyarrow==3.0.0
      - pyasn1==0.4.8
      - pycparser==2.21
      - pycryptodomex==3.14.1
      - pygments==2.12.0
      - pyjwt==2.4.0
      - pynacl==1.5.0
      - pyopenssl==20.0.1
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2022.1
      - pyyaml==6.0
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - s3transfer==0.5.2
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - secretstorage==3.3.2
      - six==1.16.0
      - snowflake-connector-python==2.5.1
      - snowflake-sqlalchemy==1.3.4
      - sqlalchemy==1.4.36
      - tabulate==0.8.9
      - threadpoolctl==3.1.0
      - typing-extensions==4.2.0
      - urllib3==1.26.7
      - websocket-client==1.3.2
      - zipp==3.8.0

